M1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mm1.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mm1/urls.py
from django.contrib import admin
from django.urls import path, include
from. import views
app_name = 'mm1'
urlpatterns = [
    path('',views.login_view,name = 'login'),
    path('logout/',views.logout_view,name='logout'),
    path('home/', views.home, name='home'),
    path('timetable_generation/', views.timetable, name='timetable'),
    path('add_room/', views.add_room, name='addroom'),
    path('add_instructor/', views.add_instructor, name='addinstructor'),
    path('instructor_list/', views.inst_list_view, name='editinstructor'),
    path('add_meetingtime/', views.add_meeting_time, name='addmeetingtime'),
    path('meetingtime_list/', views.meeting_list_view, name='editmeetingtime'),
    path('add_course/', views.add_course, name='addcourse'),
    path('course_list/', views.course_list_view, name='editcourse'),
    path('add_department/', views.add_department, name='adddepartment'),
    path('delete_meetingtime/<str:pk>/', views.delete_meeting_time, name='deletemeetingtime'),
    path('delete_course/<str:pk>/', views.delete_course, name='deletecourse'),
    path('delete_instructor/<int:pk>/', views.delete_instructor, name='deleteinstructor'),
    path('room_list/', views.room_list, name='editrooms'),
    path('delete_room/<int:pk>/', views.delete_room, name='deleteroom'),
    path('department_list/', views.department_list, name='editdepartment'),
    path('delete_department/<int:pk>/', views.delete_department, name='deletedepartment'),
    path('add_section/', views.add_section, name='addsection'),
    path('section_list/', views.section_list, name='editsection'),
    path('delete_section/<str:pk>/', views.delete_section, name='deletesection'),

]

templates/adcrs.html
{% extends 'base.html' %} {% block content %} {% load static %}

<form method="post">
  {% csrf_token %}
  <fieldset>
    <h1 class="tablink" onclick="openPage('new')" id="defaultOpen">
      Add Course
    </h1>
    <a href="{% url 'mm1:editcourse' %}"
      ><h1 class="tablink" onclick="openPage('edit')" id="link_to_edit">
        Edit Courses
      </h1></a
    >
    <div class="tabcontent" id="new">
      {{ form.as_p }}
      <input type="submit" value="Submit" class="submit" />
    </div>
  </fieldset>
</form>
<div class="img"></div>

{% endblock %}

templates/addep.html
{% extends 'base.html' %} {% block content %} {% load static %}
<form method="post">
  {% csrf_token %}
  <fieldset>
    <h1 class="tablink" onclick="openPage('new')" id="defaultOpen">
      Add Department
    </h1>
    <a href="{% url 'mm1:editdepartment' %}"
      ><h1 class="tablink" onclick="openPage('edit')" id="link_to_edit">
        Edit Department
      </h1></a
    >
    <div class="tabcontent" id="new">
      {{ form.as_p }}
      <input type="submit" value="Submit" class="submit" />
    </div>
  </fieldset>
</form>
<div class="img"></div>

{% endblock %}

templates/addmt.html
{% extends 'base.html' %} {%block content%} {% load static %}
<form method="post">
  {% csrf_token %}
  <fieldset>
    <h1 class="tablink" onclick="openPage('new')" id="defaultOpen">
      Add Meeting time
    </h1>
    <a href="{% url 'mm1:editmeetingtime' %}"
      ><h1 class="tablink" onclick="openPage('edit')" id="link_to_edit">
        Edit Meeting time
      </h1></a
    >
    <div class="tabcontent" id="new">
      {{ form.as_p }}
      <input type="submit" value="Submit" class="submit" />
    </div>
  </fieldset>
</form>

{%endblock%}

templates/addrm.html
{% extends 'base.html' %} {% block content %} {% load static %}
<form method="post">
  {% csrf_token %}
  <fieldset>
    <h1 class="tablink" onclick="openPage('new')" id="defaultOpen">Add Room</h1>
    <a href="{% url 'mm1:editrooms' %}"
      ><h1 class="tablink" onclick="openPage('edit')" id="link_to_edit">
        Edit Rooms
      </h1></a
    >
    <div class="tabcontent" id="new">
      {{ form.as_p }}
      <input type="submit" value="Submit" class="submit" />
    </div>
  </fieldset>
</form>

{% endblock %}

templates/adins.html
{% extends 'base.html' %} {% block content %} {% load static %}
<form method="post">
  {% csrf_token %}
  <fieldset>
    <h1 class="tablink" onclick="openPage('new')" id="defaultOpen">
      Add Instructor
    </h1>
    <a href="{% url 'mm1:editinstructor' %}"
      ><h1 class="tablink" onclick="openPage('edit')" id="link_to_edit">
        Edit Instructor
      </h1></a
    >
    <div class="tabcontent" id="new">
      {{ form.as_p }}
      <input type="submit" value="Submit" class="submit" />
    </div>
  </fieldset>
</form>

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <title>Timetable Scheduler</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'CSS/style.css' %}"
    />
  </head>
  <body>
    <div class="main">
      <div class="logo">
        <h2>Time_Scheduler</h2>
        <h4>Friendly AI is here for you...</h4>
      </div>
      <nav>
        <ul>
          <li>
            <a href="{% url 'mm1:home'%}"><strong>Home</strong></a>
          </li>
          <li>
            <a href="{% url 'mm1:addinstructor'%}"
              ><strong>Add Instructor</strong></a
            >
          </li>
          <li>
            <a href="{% url 'mm1:addroom'%}"><strong>Add Room</strong> </a>
          </li>
          <li>
            <a href="{% url 'mm1:addmeetingtime'%}"
              ><strong>Add Meeting time</strong></a
            >
          </li>
          <li>
            <a href="{% url 'mm1:addcourse'%}"><strong>Add Course</strong></a>
          </li>
          <li>
            <a href="{% url 'mm1:adddepartment'%}"
              ><strong>Add department</strong></a
            >
          </li>
          <li>
            <a href="{% url 'mm1:addsection'%}"><strong>Add Section</strong></a>
          </li>
          <li style>
            <form
              class="logout-link"
              action="{% url 'mm1:logout'%}"
              method="post"
            >
              {% csrf_token %}
              <button
                type="submit"
                style="
                  color: red;
                  border: 2px solid black;
                  border-radius: 20px;
                  padding: 5px;
                  cursor: pointer;
                "
              >
                <strong>Logout</strong>
              </button>
            </form>
          </li>
          <li>
            <a href="{% url 'admin:index' %}" style="border: 2px solid black;padding: 5px;margin-left: 8px;""
              >Admin Panel</a
            >
          </li>
        </ul>
      </nav>
      {% block content %} {% endblock %}
    </div>

    <!-- <script type="text/javascript">
      var checkList = document.getElementById("list1");
      var items = document.getElementById("items");
      checkList.getElementsByClassName("anchor")[0].onclick = function (evt) {
        if (items.classList.contains("visible")) {
          items.classList.remove("visible");
          items.style.display = "none";
        } else {
          items.classList.add("visible");
          items.style.display = "block";
        }
      };

      items.onblur = function (evt) {
        items.classList.remove("visible");
      }; -->
    </script>
  </body>
</html>

templates/crslist.html
{% extends 'base.html' %} {% block content %} {% load static %}

<fieldset class="fieldset">
  <a href="{% url 'mm1:addcourse'%}"
    ><h1 class="tablink" onclick="openPage('new')" id="defaultOpen">
      Add Course
    </h1></a
  >
  <h1 class="tablink" onclick="openPage('edit')" id="link_to_edit">
    Edit Course
  </h1>
  <div class="tabcontent" id="edit">
    <table class="table1">
      <thead>
        <tr class="table-headers">
          <th>Course Code</th>
          <th>Course Name</th>
          <th>Max number of students</th>
          <th class="empty"></th>
        </tr>
      </thead>

      <tbody>
        {% for crs in courses %}
        <tr>
          <td>{{crs.course_number}}</td>
          <td>{{crs.course_name}}</td>
          <td>{{crs.max_numb_students}}</td>
          <td class="empty">
            <form
              action="{% url 'mm1:deletecourse' crs.course_number %}"
              method="post"
            >
              {% csrf_token %}
              <input type="submit" value="X" class="cross" />
            </form>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</fieldset>

{% endblock %}

templates/deptlist.html
{% extends 'base.html' %} {% block content %} {% load static %}

<fieldset class="fieldset">
  <a href="{% url 'mm1:adddepartment'%}"
    ><h1 class="tablink" onclick="openPage('new')" id="defaultOpen">
      Add Department
    </h1></a
  >
  <div class="tabcontent" id="edit">
    <table class="table1">
      <thead>
        <tr class="table-headers">
          <th>Department</th>
          <th class="empty"></th>
        </tr>
      </thead>

      <tbody>
        {% for dept in departments %}
        <tr>
          <td>{{dept.dept_name}}</td>
          <td class="empty">
            <form
              action="{% url 'mm1:deletedepartment' dept.id %}"
              method="post"
            >
              {% csrf_token %}
              <input type="submit" value="X" class="cross" />
            </form>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</fieldset>

{% endblock %}

templates/index.html
{% extends 'base.html' %} {% block content %} {% load static %}

<div class="inner">
  <div class="vec">
    <div class="img">
      <img src="{% static 'img/home.jpg' %}" />
    </div>
  </div>
</div>
<div class="card">
  <div class="txt">
    <h2>Timetable Generator</h2>
    <p>
      <h3>Let AI work for you.</h3>
      Add your university class details and generate Time
      Table.
    </p>
  </div>
  <div class="crdbtn">
    <a href="{% url 'mm1:timetable' %}" class="btn">Generate Timetable</a>
  </div>
</div>
{% endblock %}

templates/login.html
{% extends 'base.html' %} {% block content %}
<div style="display: flex; margin: auto">
  <form
    class="site-form"
    action="{% url 'mm1:login' %}"
    method="post"
    style="text-align: left; width: 300px"
  >
    {% csrf_token %}
    <label for="username" style="display: block; margin-bottom: 10px"
      >Username:</label
    >
    <input
      type="text"
      id="username"
      name="username"
      style="margin-bottom: 10px; padding: 5px; width: 100%"
    /><br />
    <label for="password" style="display: block; margin-bottom: 10px"
      >Password:</label
    >
    <input
      type="password"
      id="password"
      name="password"
      style="margin-bottom: 10px; padding: 5px; width: 100%"
    /><br />
    {% if request.GET.next %}
    <input type="hidden" name="next" value="{{request.GET.next}}" />
    {% endif %}
    <input
      type="submit"
      value="Login"
      style="
        background-color: green;
        color: white;
        padding: 10px;
        border: none;
        cursor: pointer;
        width: 100%;
      "
    />
  </form>
</div>
{% endblock %}

templates/mtlist.html
{% extends 'base.html' %} {% block content %} {% load static %}

<fieldset class="fieldset">
  <a href="{% url 'mm1:addmeetingtime'%}"
    ><h1 class="tablink" onclick="openPage('new')" id="defaultOpen">
      Add Meeting time
    </h1></a
  >
  <div class="tabcontent" id="edit">
    <table class="table1">
      <thead>
        <tr class="table-headers">
          <th>PID</th>
          <th>Day</th>
          <th>Timing</th>
          <th class="empty"></th>
        </tr>
      </thead>

      <tbody>
        {% for mt in meeting_times %}
        <tr>
          <td>{{mt.pid}}</td>
          <td>{{mt.day}}</td>
          <td>{{mt.time}}</td>
          <td class="empty">
            <form
              action="{% url 'mm1:deletemeetingtime' mt.pid %}"
              method="post"
            >
              {% csrf_token %}
              <input type="submit" value="X" class="cross" />
            </form>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</fieldset>
{% endblock %}

templates/rmlist.html
{% extends 'base.html' %} {% block content %} {% load static %}

<fieldset class="fieldset">
  <a href="{% url 'mm1:addroom'%}"
    ><h1 class="tablink" onclick="openPage('new')" id="defaultOpen">
      Add Room
    </h1></a
  >
  <div class="tabcontent" id="edit">
    <table class="table1">
      <thead>
        <tr class="table-headers">
          <th>Room No.</th>
          <th>Seating Capacity</th>
          <th class="empty"></th>
        </tr>
      </thead>

      <tbody>
        {% for rm in rooms %}
        <tr>
          <td>{{rm.r_number}}</td>
          <td>{{rm.seating_capacity}}</td>
          <td class="empty">
            <form action="{% url 'mm1:deleteroom' rm.id %}" method="post">
              {% csrf_token %}
              <input type="submit" value="X" class="cross" />
            </form>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</fieldset>

{% endblock %}

templates/seclist.html
{% extends 'base.html' %} {% block content %} {% load static %}

<fieldset class="fieldset">
  <a href="{% url 'mm1:addsection'%}"
    ><h1 class="tablink" onclick="openPage('new')" id="defaultOpen">
      Add Section
    </h1></a
  >
  <div class="tabcontent" id="edit">
    <table class="table1">
      <thead>
        <tr class="table-headers">
          <th>Section Id</th>
          <th>Department</th>
          <th>Total Classes</th>
          <th class="empty"></th>
        </tr>
      </thead>

      <tbody>
        {% for sec in sections %}
        <tr>
          <td>{{sec.section_id}}</td>
          <td>{{sec.department}}</td>
          <td>{{sec.num_class_in_week }}</td>
          <td class="empty">
            <form
              action="{% url 'mm1:deletesection' sec.section_id %}"
              method="post"
            >
              {% csrf_token %}
              <input type="submit" value="X" class="cross" />
            </form>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</fieldset>

{% endblock %}

templates/timetable.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

{% for section in sections %}
<h2 class="secHead">{{ section.section_id }} ({{ section.department }})</h2>
    <table class="table2">
      <colgroup>
        <col >
        <col >
        <col>
        <col>
        <col >
        <col>
      </colgroup>
      <tr>
        <th>Class #</th>
        <th>Course</th>
        <th>Venue(Block- Room)</th>
        <th>Instructor</th>
        <th>Class Timing</th>
      </tr>
      {% for class in schedule %}
        {% if class.section == section.section_id %}
        <tr>
          <th>{{class.section_id}}</th>
          <td>{{class.course}}</td>
          <td>{{class.room}}</td>
          <td>{{class.instructor}}</td>
          <td>{{class.meeting_time}}</td>
        </tr>
        {% endif %}
      {% endfor %}
    </table>

{% endfor %}
  <div class="extra">

  </div>
{% endblock %}